#!/usr/bin/env python3
"""Extract an icon image from a .ico file and emit it as a C header holding
ARGB32 (network byte order) pixel data, the format StatusNotifierItem's
IconPixmap property wants. Used by the mq-tray-helper build (Linux cross
build only).

Usage: gen_tray_icon.py <input.ico> <output.h> [preferred_size]
"""

import struct
import sys


def main() -> int:
    ico_path = sys.argv[1]
    out_path = sys.argv[2]
    preferred = int(sys.argv[3]) if len(sys.argv) > 3 else 48

    data = open(ico_path, "rb").read()
    count = struct.unpack_from("<HHH", data, 0)[2]

    # Collect 32bpp BMP (DIB) entries: (width, height, offset, size)
    entries = []
    for i in range(count):
        w, h, _colors, _res, _planes, bpp, size, off = struct.unpack_from(
            "<BBBBHHII", data, 6 + i * 16)
        w = w or 256
        h = h or 256
        if bpp == 32 and not data[off:off + 8].startswith(b"\x89PNG"):
            entries.append((w, h, off, size))
    if not entries:
        print("no 32bpp BMP entries in icon", file=sys.stderr)
        return 1

    # Pick the entry closest to the preferred size (prefer >=)
    entries.sort(key=lambda e: (abs(e[0] - preferred), -e[0]))
    w, h, off, size = entries[0]

    # DIB: BITMAPINFOHEADER (biHeight doubled for the AND mask), then BGRA
    # rows bottom-up, then a 1bpp AND mask we can ignore for 32bpp icons.
    bi_size = struct.unpack_from("<I", data, off)[0]
    pixels = data[off + bi_size: off + bi_size + w * h * 4]

    argb = bytearray(w * h * 4)
    for y in range(h):
        src_row = (h - 1 - y) * w * 4
        dst_row = y * w * 4
        for x in range(w):
            b, g, r, a = pixels[src_row + x * 4: src_row + x * 4 + 4]
            argb[dst_row + x * 4: dst_row + x * 4 + 4] = bytes((a, r, g, b))

    with open(out_path, "w") as f:
        f.write("/* Generated by gen_tray_icon.py from %s - do not edit. */\n" % ico_path.split("/")[-1])
        f.write("#pragma once\n\n")
        f.write("#define MQ_TRAY_ICON_WIDTH  %d\n" % w)
        f.write("#define MQ_TRAY_ICON_HEIGHT %d\n\n" % h)
        f.write("static const unsigned char mq_tray_icon_argb[%d] = {\n" % len(argb))
        for i in range(0, len(argb), 16):
            f.write("    " + ",".join(str(b) for b in argb[i:i + 16]) + ",\n")
        f.write("};\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
